target 'PlanetNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for PlanetNews
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', :inhibit_warnings => true
end
